### ISSUE TITLE
TODO : Patch spacechase0/ContentPatcherAnimations

### ISSUE THREAD

**Issue by ameisen** [ameisen/SV-SpriteMaster#1]
Pending an update to CPA, write a harmony patch in SpriteMaster to adjust [ContentPatcherAnimations](https://github.com/spacechase0/ContentPatcherAnimations) so that updating the animation is not a `GetData/SetData`, but rather is a direct patch to Draw. This is probably more difficult that it seems.

**Comment by Traehgniw** [comment]
oh _this_ is why my daffodils and sap are flickering, because of those CPA fish i have

**Comment by ameisen** [comment]
CP:A was handled in a completely different way, and now works properly in SpriteMaster due to the Suspended Sprite Cache.
