### ISSUE TITLE
InvalidOperationException during Schedule Parsing

### ISSUE THREAD

**Issue by shekurika** [ameisen/SV-SpriteMaster#12]
Potential SM bug reported by Skuuurt#0746 on SVE's discord.
[https://smapi.io/log/b41c468f8e384b5289b607e9f8e1b504](https://smapi.io/log/b41c468f8e384b5289b607e9f8e1b504)

An InvalidOperationException occurs when parsing SVE Sophias Schedule apparently.

**Comment by ameisen** [comment]
I haven't seen this reported recently and have not been able to reproduce it, so it was likely fixed in one of the July 30, 2022 commits.
