### ISSUE TITLE
Investigate compatibility with Dynamic Reflections

### ISSUE THREAD

**Issue by Floogen** [ameisen/SV-SpriteMaster#14]
As requested, I have opened an issue regarding compatibility with [Dynamic Reflections](https://www.nexusmods.com/stardewvalley/mods/12831).

Please do let me know if any changes are needed on my side; I will do my best to accommodate them!

**Comment by ameisen** [comment]
From what I can tell, it appears to be fully compatible (or at least not doing anything that breaks with SM) though I'll keep it under observation.
