### ISSUE TITLE
replace pathfinding with faster algorithm

### ISSUE THREAD

**Issue by RealSweetPanda** [ameisen/SV-SpriteMaster#34]
SpriteMaster currently uses Dijkstra for pathfinding, but it is slower compared to A*.

I also read that A* is considered an extension to Dijkstra so maybe implementing it won't require completely rewriting the code

**Comment by ameisen** [comment]
As you said, A* is an extension to Dijkstra's pathfinding algorithm which adds a heuristic to select the next node.

SpriteMaster doesn't use A* as there is no meaningful heuristic to use, as the nodes do not have distances nor positions. Theoretically, one could try to generate synthetic ones based on node connections, but that wouldn't offer much improvement.
